name: Generate Datas
2
​
3
on:
4
  schedule: # execute every 12 hours
5
    - cron: "* */12 * * *"
6
  workflow_dispatch:
7
​
8
jobs:
9
  build:
10
    name: Jobs to update datas
11
    runs-on: ubuntu-latest
12
    steps:
13
      # Snake Animation
14
      - uses: Platane/snk@master
15
        id: snake-gif
16
        with:
17
          github_user_name: IsLSteven
18
          svg_out_path: dist/github-contribution-grid-snake.svg
19
​
20
      - uses: crazy-max/ghaction-github-pages@v2.1.3
21
        with:
22
          target_branch: output
23
          build_dir: dist
24
        env:
25
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
26
​
